### ISSUE TITLE
suggest that server options add host 

### ISSUE THREAD

**Issue by Zyingying** [Tofandel/prerenderer#25]
```
 const baseURL = `http://localhost:${rootOptions.server.port}`
```
change to
```
 const baseURL = `http://${rootOptions.server.host}:${rootOptions.server.port}`
```

I want to change the host, but cannot

**Comment by Tribex** [comment]
@Zyingying Are you trying to use a different server, or have the prerenderer server listen on a different hostname? If the former, that will not work due to tight coupling between the server and client for prerenderer. If the latter, I'm not sure why you would want to do that. Could you explain further?

**Comment by Zyingying** [comment]
former
