### ISSUE TITLE
Why did route become the homepage 

### ISSUE THREAD

**Issue by clarehjh** [Tofandel/prerenderer#69]
![image](https://user-images.githubusercontent.com/83281667/229445792-fd989d3c-4d9a-41fb-8a2d-67d0ec9a0b00.png)

**Comment by clarehjh** [comment]
我想渲染这样的路由实际却之渲染其中一个，有什么办法渲染两个路径呢
![image](https://user-images.githubusercontent.com/83281667/229455860-a8334d24-ca7e-42e9-ba14-8ba2236fe6b1.png)

**Comment by Tofandel** [comment]
You must have a redirect in your `eduction` page (Maybe due to typo) the prerenderer by default follows redirect

For query strings, you would need to customize the `postProcess` to change the output file to be output with a query string and then customize your nginx/apache to serve the correct file based on the query string. It's possible but out of the scope of this lib, because we output files that will work with a default web server, so I won't write a tutorial for you

**Comment by clarehjh** [comment]
This is my question. I found out that the reason is that my login was blocked, so I was redirected to/. Thank you very much for your answer🥹
