### ISSUE TITLE
Configuration to prerender alongside the standard build?

### ISSUE THREAD

**Issue by idank** [Tofandel/prerenderer#70]
I managed to follow the readme to get my Vue 3 / Vite app prerendered, basically by adding:

```
prerender({
      routes: ["/"],
      renderer: "@prerenderer/renderer-puppeteer",
      postProcess(renderedRoute) {
        // Replace all http with https urls and localhost to your site url
        renderedRoute.html = renderedRoute.html
          .replace(/http:/i, "https:")
          .replace(
            /(https:\/\/)?(localhost|127\.0\.0\.1):\d*/i,
            process.env.CI_ENVIRONMENT_URL || ""
          );
      },
    }),
```

to my `vite.config.ts`. But this (expectedly) changes my regular `vite build`.

Is it possible to alter the config in a way that allows a regular build and a "prerender build" to coexist?

**Comment by Tofandel** [comment]
Do you mean you want 2 separate commands? On to build and one to prerender?

It's not possible to just prerender because the renderer actually needs access to the list of built files as it uses those during the rendering phase

But you can still have 2 commands, one to build normally and one to build with the prerenderer

Just use an environment variable

If you really want to separate the renderer completely you'd need to make a separate js script, import the `@prerenderer/prerenderer` package and not the vite plugin and configure it based on your projects dir structure, you might need to modify the server to always route to the index.html file

Then just add that script as a npm command
