### ISSUE TITLE
Duplicate elements in <head>

### ISSUE THREAD

**Issue by idank** [Tofandel/prerenderer#72]
The output of prerender appears fine on disk, e.g.:

```
<!DOCTYPE html>
<html lang="he" dir="rtl">

<head>
    <meta charset="UTF-8">
    <style type="text/css">
       ...
    </style>
    <link rel="icon" href="/assets/logo-189b1cf6.svg">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script type="module" crossorigin="" src="/assets/index-5bd76bc5.js"></script>
    <link rel="stylesheet" href="/assets/index-de5a37e2.css">
</head>

...
```

But when loading the prerendered page in a browser, some elements in `<head>` get duplicated, e.g. the `<style>`, and some `<meta>` (omitted for clarity).

Is this because the javascript in the page is essentially executed twice? Once by prerenderer, second time by the browser when loading the prerendered page? If so, how does the rest of the page look OK?

Thanks.

**Comment by idank** [comment]
I disabled javascript and the duplication stopped.

**Comment by Tofandel** [comment]
> Is this because the javascript in the page is essentially executed twice? Once by prerenderer, second time by the browser when loading the prerendered page? If so, how does the rest of the page look OK?

Yes exactly, if you are using vue, the page looks ok because it's rerender on top of the existing elements

The issue is that your scripts are adding `script` , `head` or other tags outside of your application that are not checked for uniqueness by id or other systems

To prevent this you can check for `if (window.__PRERENDER_INJECTED || process.env.node_env !== 'production')` before adding your scripts and styles (or the opposite `if (!window.__PRERENDER_INJECTED)`) to only output execute the part that edits the markup when prerendering or not prerendering based on your preference (the first option is a bit harder to handle because you might still want to execute the code in dev mode when the plugin doesn't exists which is why I added `process.env.node_env` which might not be defined in your bundler)
