### ISSUE TITLE
routes support path like /case/**/*

### ISSUE THREAD

**Issue by bobby169** [Tofandel/prerenderer#90]
Can routes support path like /case/**/* ?

```js
export const prerenderConfig = prerender({
  routes: ['/', '/case/**/*']
```

**Comment by Tofandel** [comment]
No it would not be possible because we have no way to know how to generate a list of the routes, we must visit all routes and generate one html file per route

If you do have a router file in your app, then you can import it and try to generate a list of routes from it, you could also query the database if needed to build the route list but it's not something we can do for you
