### ISSUE TITLE
Renderer should not believe to window.location.pathname

### ISSUE THREAD

**Issue by a0s** [Tofandel/prerenderer#96]
I have vue3 project with path-based localization controlling. 
When user go to `/es/page` inner script change locale to `es` (with updating translations) and update router to `/page`. 
When i ask prerender `routes: ['/es', '/es/page']` it creates `/es` and `/page` instead of `/es` and `/es/page`

I have a strong suspicion that [this block of code](https://github.com/Tofandel/prerenderer/blob/dev/packages/renderer-puppeteer/src/Renderer.ts#L170-L174) should look like this:
```ts
const result: RenderedRoute = {
  originalRoute: route,
  route: route,  // <= should use initial `route` parameter
  html: await page.content(),
}
```

This can be changed directly, or done as a global option or a path-specific option (whether to trust window.location.pathname for a specific path or not). Unfortunately, I'm not a big expert on packaging npm packages and I can't quickly fix this for myself.

**Comment by Tofandel** [comment]
It is by design, if you ask to prerender `/es/page` and your page redirects it to `/page` then this is where we render the page, because we assume that the user will be redirected there by the server and that's where the html of the page actually resides, otherwise reloading the page would result in a content discrepancy

Basically the prerendering structure will always match the actual urls on the app and changing this would create more issues than it solves

**Comment by Tofandel** [comment]
You can always control this using the [postProcess option](https://github.com/Tofandel/prerenderer?tab=readme-ov-file#prerenderer-options) but be aware of the caveats

```js
postProcess (renderedRoute) { 
   renderedRoute.route = renderedRoute.originalRoute
},
```

**Comment by a0s** [comment]
@Tofandel thank you! this works like a charm!
